// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.TShirt.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4579.TShirt.Robot;
import edu.wpi.first.wpilibj.Timer;

/**
 *
 */
public class Shoot extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	
	private enum SHOOTSUBSTATETYPE {VALVE_OPEN, VALVE_CLOSED}
	
	private SHOOTSUBSTATETYPE m_shootSubstate = SHOOTSUBSTATETYPE.VALVE_CLOSED;
	private Timer             m_shootTimer    = new Timer();
	private double            m_stopTime      = 0.0;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Shoot() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.compressedAirTank);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	m_shootTimer.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	if (m_shootSubstate == SHOOTSUBSTATETYPE.VALVE_CLOSED) {
    		
    		// Compute how long to leave the valve open            
    		m_stopTime = (double)Robot.compressedAirTank.getValveOpenTime() / 1000.0; // Convert from ms to secs.
           
           // Open the valve
           Robot.compressedAirTank.openTankValve();
           
           // Remember that it is open
           m_shootSubstate = SHOOTSUBSTATETYPE.VALVE_OPEN;
    	   
    	   // Start a timer to keep track of how long the valve is open.
           m_shootTimer.start();
    	   }
    	else {
    		
    		// The valve is open.  Check to see if the shoot time has expired.

           
            // if time to close the valve
    	    if (m_shootTimer.get() >= m_stopTime) {
    		   // Close the valve and reset the timer.
    	       Robot.compressedAirTank.closeTankValve();
    	       m_shootSubstate = SHOOTSUBSTATETYPE.VALVE_CLOSED; 
    	       m_shootTimer.stop();
    	       m_shootTimer.reset();
    	    }
    	}
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return m_shootSubstate == SHOOTSUBSTATETYPE.VALVE_CLOSED;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
